markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Matt Warren 
url: http://mattwarren1234.github.io
description: A fantastic blog that is fantastic.
twitter: mattwarrensays
